# This workflow will install Python dependencies and lint
name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  publish-to-pypi:
    name: >-
      Publish Python 🐍 distribution 📦 to PyPI
    #if: startsWith(github.ref, 'refs/tags/')  # only publish to PyPI on tag pushes
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/wayfire
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install
      run: |
          python -m pip install --upgrade pip
          sudo apt-get install libdbus-1-dev
          pip install -r requirements.txt
          pip install setuptools wheel
          python3 -m pip install .
          python -m pip install -U build
          python3 -m build
          
    - name: Download all the dists
      uses: actions/download-artifact@v3
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1

